apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: hotpod
    includeSelectors: true

resources:
  - deployment.yaml
  - service.yaml
  - pdb.yaml
