apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hotpod-with-sidecar
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hotpod-with-sidecar
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: ContainerResource
      containerResource:
        name: cpu
        container: hotpod
        target:
          type: Utilization
          averageUtilization: 50
