[global]
disable = []

exclude = [
    ".cache",
    "bin",

    ".git",
    ".github",
    ".idea",
    ".vscode",
]

respect-gitignore = true

flavor = "gfm"

[MD003]
style = "atx"

[MD004]
style = "dash"

[MD007]
indent = 2

[MD013]
line-length = 120
code-blocks = false
reflow = true
reflow-mode = "default"

[MD041]
front_matter_title_pattern = '^name\s*[:=]'

[MD044]
names = []
code-blocks = false
